[package]
name = "book-gen"
version = "1.0.0"
edition = "2018"
authors = ["Joshua Price <me@jwpjr.tech>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
logos = "0.12.0"
clap = "3.0.0-beta.5"
